### ISSUE TITLE
Improving Portability

### ISSUE THREAD

**Issue by Pharap** [MrBlinky/ArduboyFX#5]
Portability might not be one of your prime concerns, but in case you are concerned with it, there's a few things that would make the library easier to port.

Firstly, instead of including `Arduboy2.h` in the header, it could be relegated to the `.cpp` file because nothing about the public API relies on anything Arduboy2 defines, it's only the back-end that depends upon it.

Consequently you'd need to include at least `stdint.h` to get the fixed-width types (`uint8_t`, `uint16_t` et cetera) and one of the Arduino headers (I'm not sure which) to get the `PORT` macros (`PORTD`, `PORTD2` et cetera), but that should be all.

Secondly, you could replace the use of `_BV` with (`1 <<`). `_BV` doesn't really do anything special. If anything it just obfuscates the code since it's not obvious what `_BV` means or does to anyone who doesn't know Arduino in-depth, whilst `1 <<` is amlost universally recognised and understood.

Thirdly, you could replace the GCC-specific `__attribute__`s with [the standardised attribute syntax](https://en.cppreference.com/w/cpp/language/attributes). The advantage here is that the code will still compile on a compiler that doesn't recognise GCC's `__attribute__` syntax, and it will ignore any attribute that it doesn't recognise/understand, which in most cases will still produce reasonable behaviour.

In particular;
* `__attribute__((always_inline))` → `[[gnu::always_inline]]`
* `__attribute__((noinline))` → `[[gnu::noinline]]`
* `__attribute__((naked))` → `[[gnu::naked]]`
* `__attribute__ ((noinline)) __attribute__ ((naked))` → `[[gnu::noinline, gnu::naked]]`

E.g.
```cpp
[[gnu::noinline, gnu::naked]]
static uint16_t readPendingUInt16();
```

If you're happy with these changes, I'm happy to make a PR for them.
Unlike the changes mentioned in #4 these should be non-breaking (provided nobody is neglecting to include `Arduboy2.h` at the same time as `FX.h`).

**Comment by MrBlinky** [comment]
feel free to change the header includes.

note that _BV is not an Arduino specific macro but an AVR macro defined in sfr_defs.h

I wasn't aware of the attributes being gcc specific. Feel free to update them to the standard format

**Comment by Pharap** [comment]
>feel free to change the header includes.

I'll see what I can do.
That one I'll probably have to actually set up a test environment for to make sure I don't accidentally neglect a header.
(As it was I nearly forgot that `stddef.h` would be needed for `size_t`.)

>note that _BV is not an Arduino specific macro but an AVR macro defined in sfr_defs.h

So it is. I'd seen it used heavily in the AVR version of Arduino so I'd misremembered it being Arduino that actually defines it.

Either way it's not a standard macro, so someone trying to port this to e.g. ARM or desktop would have to go out of their way to deal with it, whereas `1 <<` is universal.

>I wasn't aware of the attributes being gcc specific.

Clang also recognises them because the Clang devs went out of their way to be GCC compatible, but MSVC will choke on them because MSVC uses `__declspec` instead of `__atrribute__` and has a different pool of attributes, and I think the rules for where `__declspec` may appear might even be different to GCC. (I dread to think what the situation would be with other compilers. E.g. Intel's overpriced compiler.)

That awkward situation is precisely why the C++ committee agreed to create the standardised attribute syntax for C++11. It certainly saves people having to cook up awkward macros that attempt to do the right
